### PR TITLE
removed rocket from the throw expression

### PR DESCRIPTION
**Pull request by oyilmaztekin**
Rocket for `throw expression` has been removed from the list. This was discussed at the [January meeting](https://github.com/tc39/tc39-notes/blob/master/es8/2018-01/jan-24.md#13iiii-throw-expressions-for-stage-3) and decided to discuss again. `Richer Keys`, `Array.prototype.{flat,flatMap}`, `Object.fromEntries` are ready and will be discussed in the [68th meeting](https://github.com/tc39/agendas/blob/4fc4eff3afedf26d6951bc14f810c1185b02e9ee/2019/01.md)

[issue#161](https://github.com/tc39/proposals/issues/161)

### CODE REVIEW

**Comment by ljharb** [comment]
That's up to @rbuckton; the rocket doesn't just mean "will be presented for advancement at the next meeting".

**Comment by oyilmaztekin** [comment]
If that so, I think it would be better to close this PR and continue this discussion in the #161 if it's necessary. It is obvious that there is a misunderstanding or maybe I may not understand the circumstances of the proposal. Because it seems to me like the result of the proposal it's uncertain. Concerning the conclusion of the January meeting notes, I decided to make this changing.

>RBN: conclusion: not moving to stage 3, want to address concerns, maybe offline, maybe grammar changes to make it more viable as an option,

>Conclusion/Resolution
not moving to stage 3

**Comment by ljharb** [comment]
Ah, that certainly does imply that the rocket should be removed! However, I think we should wait for @rbuckton to chime in.

**Comment by ljharb** [comment]
Rockets have now been removed in #174.

**Pull request closed without merging**
