### PR TITLE
Update name and link for Null Propagation -> Optional Chaining

### PR DESCRIPTION
**Pull request by sudowork**
Update the name of the proposal from "Null Propagation" to "Optional Chaining". Also, link to the TC39 proposal repo tc39/proposal-optional-chaining instead of the slides for Null Propagation.

### CODE REVIEW

**Comment by sudowork** [comment]
@gisenberg @claudepache

**Comment by ljharb** [comment]
Thanks; generally only proposal champions should update their own entries. I'll tag them and see if this is OK.

**Comment by littledan** [comment]
Note that this PR is updating the name to match what's written on the explainer and draft spec.

**Comment by sudowork** [comment]
@ljharb, looks like @claudepache approved.

**Pull request merged**
