### PR TITLE
Update 'global' proposal to 'globalThis'

### PR DESCRIPTION
**Pull request by concavelenz**
for consistency with was agreed upon.

### CODE REVIEW

**Comment by kiding** [comment]
For reference, the rationale and discussion can be found here: https://github.com/tc39/proposal-global/issues/20

**Comment by jsg2021** [comment]
I don't follow, the proposal was renamed? or the identifier as well? This PR just seems to rename the link label.

**Comment by chicoxyzzy** [comment]
@jsg2021 Identifier was changed due to [web compatibility issues](https://github.com/tc39/proposal-global/issues/20)

**Comment by jsg2021** [comment]
Ah, thanks. the name `globalThis` hurts my eyes, but oh well. :P

**Pull request merged**
