### PR TITLE
Add an “author” column to each table

### LINKED ISSUE #93: Distinguish authors from champions
Can we please add an “author” column and distinguish authors from champions?

Context: I’m championing multiple proposals from community members. I don’t want credit for *writing* these proposals, though. It feels wrong to conflate being a champion with authorship.

Despite me explicitly mentioning the proposal authors during each of my presentations, some committee members mistakenly thought _I_ was the author.

I’ve seen similar confusion in articles and blog posts about proposals, where a champion was credited as an author, based on the table in this repository.

### PR DESCRIPTION
**Pull request by mathiasbynens**
Closes #93.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
ProTip™: [`prettier`](https://github.com/prettier/prettier) can auto-format these tables. `prettier README.md`

**Comment by mathiasbynens** [comment]
Added the column to the finished proposals list as well.

**Comment by mathiasbynens** [comment]
And to the `Intl` tables! Let’s get this merged.

**Comment by ljharb** [comment]
Thanks! I'll do the rebase, and we'll get this in.

**Comment by littledan** [comment]
Thanks for this improvement!

**Pull request merged**
