### PR TITLE
Add Unicode property escapes in regular expressions proposal

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by mathiasbynens** [comment]
As a side note, since all these are Stage 0 proposals, I think we can get rid of the “Stage” column. Also, the “Champion” column should be renamed to “Authors + Champions” based on its current contents. I’ll submit a PR for that once this is merged.

**Comment by mathiasbynens** [comment]
Also it’s not entirely clear from the document what “Stage 0 proposals have been presented to the committee” means exactly. Does e.g. emailing es-discuss count as presenting it, or is that only possible at a TC39 meeting? (The phrasing makes me think it’s the latter, but there several of the listed proposals haven’t been presented at any meeting.)

**Comment by michaelficarra** [comment]
As I recall from the meeting where this was presented, @bterlson wants to advance each of the RegExp enhancements together. I'd rather see just one entry in the table which refers to all of the RegExp enhancements.

**Comment by mathiasbynens** [comment]
Respectfully, I don’t think that makes much sense, as the proposals aren’t interdependent.

**Comment by littledan** [comment]
@michaelficcara I  think it makes sense to advance these separately. The proposals are not interdependent, and this one in particular has an implementation and spec text, unlike some others. This proposal and no others are on the agenda for advancement at the next meeting.

**Comment by ljharb** [comment]
@michaelficarra the "stage" column is there to allow easy cut-and-pasting from "stage 0" to "active proposals" when applicable.

The "stage 0" proposals have generally been "proposals presented to the committee", or "proposals planned to be presented by a TC39 champion", or "proposals left over from Harmony". Something without an identified champion, while [technically](https://tc39.github.io/process-document/) allowed in stage 0, isn't really useful to list yet.

**Comment by michaelficarra** [comment]
@mathiasbynens If you can find @bterlson's slides from that presentation (which *should have* been linked to from the notes), you'll see that he made that request. He used some strange food metaphor.

**Comment by littledan** [comment]
@michaelficarra In personal communication, Brian and I have agreed to co-champion this single part. IIRC the 'buffet' metaphor was more about, you can take what you want without the things you don't want.

**Pull request merged**
