### PR TITLE
Add switch return proposal

### PR DESCRIPTION
**Pull request by gmarcos87**
https://github.com/gmarcos87/switch-return-proposal

### CODE REVIEW

**Comment by ljharb** [comment]
@gmarcos87 hi, which ecma member do you represent?

if none, please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal - this repo is only for championed proposals.

**Comment by gmarcos87** [comment]
I'm sorry, I will close this pull request

**Comment by DaveLomber** [comment]
@gmarcos87 were you able to push this forward?

**Comment by nicolo-ribaudo** [comment]
@DaveLomber Something similar is being pursued in https://github.com/tc39/proposal-pattern-matching

**Pull request closed without merging**
