### PR TITLE
add firefox status to stage 2+ proposals

### PR DESCRIPTION
**Pull request by codehag**

### CODE REVIEW

**Comment by ljharb** [comment]
PR intended for a fork?

**Comment by leobalter** [comment]
To be fairly honest, the content is great as the [Mozilla Standards Positions](https://mozilla.github.io/standards-positions/) is. This information might be too costly for maintenance here but it's definitely something we should consider adding in the future.

**Comment by ljharb** [comment]
We could maybe add a column to stage 2+ proposals that contains a `<details>` that expands to show engine support?

**Comment by leobalter** [comment]
I don't have a preferred format, and I'd celebrate any easy way to get to this information quickly for each proposal listed.

**Comment by ljharb** [comment]
I mean, you should expect to find that info at http://kangax.github.io/compat-table/esnext/ anyways :-)

**Comment by leobalter** [comment]
Well, what I want is slightly different from what Kangax provides. The information I like here is a quick link to the bug tracker for the implementation in a specific runtime (Firefox, Chrome, WebKit, etc) or information it's not open yet. Additionally status of this filed bug (if any): open, wip, done. If it's "done", then yes, possibly the version it's been released. This last information is the least that I want. 

My goal is to find ways to observe development of a feature and perhaps offer help or identify challenges.

**Comment by leobalter** [comment]
Just to give an example: `top-level-await` in the [table here](https://github.com/tc39/proposals/pull/280/files#diff-04c6e90faac2675aa89e2176d2eec7d8). I know it's open - or "available". This means, we already have an issue in Fx's bug tracker but we need to set some traction.

**Comment by codehag** [comment]
ah yeah... sorry about the misplaced pr -- i was trying to merge it into my fork for maintaining a list of where we are with ff -> https://github.com/codehag/proposals

but github defaults to the origin fork, and not the local master. if you want to observe how ff is moving through the proposals feel free to follow that repo. don't know if it makes sense for the main proposal repo as we would have a few engines to track.

I was thinking of adding this kind of info to the proposal template tho

**Pull request closed without merging**
