### PR TITLE
`each` instead of `forEach`

### PR DESCRIPTION
**Pull request by zwhitchcox**

### CODE REVIEW

**Comment by slikts** [comment]
https://en.wikipedia.org/wiki/Foreach_loop

It's more of an idle thought than a proposal. You should at least post to esdiscuss first.

**Comment by zwhitchcox** [comment]
Ok, I have applied to esdiscuss, but I can't post anything until they approve my membership apparently.

And I don't agree with you that it's an idle thought versus a proposal. "Idle" meaning "not to be acted upon" does not describe my sentiment toward this proposal. I would very much like this to be acted upon. The first action that should be taken, according to you, would be review in a TC39 meeting. The next action would be adding it to this repository (I suppose). Then, adding it to transpilers, and then, adding it to the actual browsers.

Due to the nature of my proposal, I fail to see any basis for your allegation that it is an "idle thought".

**Comment by zwhitchcox** [comment]
I will close this for now though until I have a champion

**Comment by rwaldron** [comment]
I haven't tested this but it will likely be impossible to add a method called `each` to Array.protoype, due to the presence of a method with the same name in the following libraries:

- http://mootools.net/core/docs/1.6.0/Types/Array#Array:each
- http://sugarjs.com/api/Array/each


More discussion: 

- https://esdiscuss.org/topic/having-a-non-enumerable-array-prototype-contains-may-not-be-web-compatible 
- https://esdiscuss.org/topic/array-prototype-contains-solutions


Also, if `each` is only a change of spelling from `forEach`, I doubt the proposal will have any support.

**Comment by zwhitchcox** [comment]
Pardon my ignorance, but why do we care if it breaks some people's libraries? The specification has never committed to keeping those words unused, right? And wouldn't it be trivial for those libraries to change the word? I thought you weren't supposed to alter the prototype anyway. And isn't the efficiency and aesthetics of the entire language more important than some library someone wrote?

**Comment by rwaldron** [comment]
I believe your questions are all answered in this discussion threads I posted. It's unfair to expect me to also provide a summary ;P

**Comment by zwhitchcox** [comment]
Oh, no, really sorry, I'll have to read those after work, and I didn't realize those would answer the question. Thank you.

**Comment by gsklee** [comment]
@rwaldron Interesting reading materials, thanks! To recapitulate:

* Everyone was actually against renaming `contains` to something less accurate simply because of MooTools' bad implementation - except one of the browser vendors
* A few workarounds were briefly explored but no instant consensus could be reached
* The champion of the proposal was afraid of the feature may "never shipped" and made the compromise of renaming

While this discussion began as something far from an ample thought, it indeed surfaced a few questions still waiting to be answered:

* What happens now if we're going to add `Array.prototype.flatten`? Or any other new instance methods whose most accurate names have already been used by some *badly-implemented-but-still-out-in-the-large* libs?
* Suboptimal solutions can make ways into the standard due to complications under a specific background, but why can't we fix some of those easily-fixable compromises when the original concerns are no longer valid? Why would we allow the future of the language to be shaped by compromises?

IMHO, all these suboptimal naming issues (`includes` instead of `contains`, `forEach` instead of `each`, etc.) can be very easily fixed if we propose a spec change like:

1. Replace the name of `Array.prototype.forEach`([§ 22.1.3.10](http://www.ecma-international.org/ecma-262/7.0/#sec-array.prototype.foreach)) to `Array.prototype.each`
2. Add a new definition of `Array.prototype.forEach` which points to `Array.prototype.each`, and specify **a sunset time** for this alias; for example, "this alias will be removed by the 13th Edition" (by 2022)

I'd say 5 years is enough time and no more excuse for the MooTools shenanigans and the like.

Simply adding aliases is one thing, and one thing I do not support - we don't want to open a bad precedent that foreseeably leads to aliases all over the place.

But fixing compromises has totally another meaning, and I do not want to see compromises stay.

**Comment by jorendorff** [comment]
> I'd say 5 years is enough time and no more excuse for the MooTools shenanigans and the like.

It sounds like you think that if Firefox removed `forEach` and some web sites broke, then we could just say "there's no excuse for still using `forEach` in the year 2022" and that would be that. What would actually happen is, we would break a lot of web sites, and all those web sites' users would be forced to switch to Chrome.

If we somehow convinced all browser vendors to cooperate and remove the feature at the same time, then what would happen instead is: we would break a lot of web sites, and all those web sites' users would have no recourse. Some sites would get fixed. Others would not.

We don't build the web to indulge our own sense of tidiness. We build it for other people.

Those people want things to work. They are sad when things stop working. It's hard enough to keep stuff working without deliberately breaking backward compatibility.

> I do not want to see compromises stay.

You need to look for some other use for your time than working on web standards, then! It's compromises all the way down.

**Comment by gsklee** [comment]
Hi @jorendorff, I appreciate the majority of your input which perfectly explained the concerns from a browser vendor's standpoint, but I do not appreciate your last line of tongue-in-cheek. There are loads of tons of JavaScript developers out there on this planet, but only a handful few would make the conscious decision to find their ways here. We're here because we all have the benign intent to help. Asking someone to turn around and get lost simply because he doesn't resonate with yours, or your organization's POV, is just disrespectful.

--

There are some assumptions going on here that I'd like to disagree:

> **Browsers must not break websites**

Browsers are already doing this all the time. Think about websites being built upon [VML](https://en.wikipedia.org/wiki/Vector_Markup_Language), ActiveX, Flash, etc. A governmental social welfare portal in my country[[1]](http://ulife.taipei.gov.tw/) still has the entirety of their website in Flash - would that prevent all the browser vendors from pulling the plug?

> **Browsers must not break standards-compliant websites**

E4X ([ECMAScript for XML](https://en.wikipedia.org/wiki/ECMAScript_for_XML)) has been a web standard (ECMA-357) and implemented in Firefox for a decade (2004/2005 - 2014). I am sure there were at least some standards-compliant websites that gone broken in the wild when the plug was pulled as well.

> **People are sad when things stop working**

And who are these people? If we're discussing some W3C standards, then yeah, they are must likely normal people. But we're talking about JavaScript, and our target audience is developers, not normal people. And developers know how to cope with code updates.

Even if we're talking about normal people who copied their code from somewhere else, the scenario that most likely will follow is that they'll go to the source of the code snippet (or just google their ways) to the updated version of code.

> **We never have a precedence where all major ECMAScript implementers are asked to remove something that was previously in the standard**

No - and that's the fear and feeling of uncertainty we need to battle here. *5 years* is just a pretty arbitrary time length I made up to probe people's reactions. Let's make a compromise - how about *100 years*? I've done my homework and there are indeed methods inside the latest standard (ES2016) that have been marked as deprecated on MDN (eg. [`String.prototype.big()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/big); more at [[2]](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features)) and been put in Annex B. Per their respective descriptions:

**MDN**
```
[...D]eprecated features can still be used, but should be used with caution because they are
expected to be removed entirely sometime in the future. You should work to remove their use
from your code.
```
```
This feature has been removed from the Web standards. Though some browsers may still support
it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web
apps using it may break at any time.
```

**ES2016 Language Spec**
```
This annex describes various legacy features and other characteristics of web browser based
ECMAScript implementations. All of the language features and behaviours specified in this annex
have one or more undesirable characteristics and in the absence of legacy usage would be removed
from this specification. However, the usage of these features by large numbers of existing web
pages means that web browsers must continue to support them. [...]
```

Is it safe to assume that a century's time is enough to attain "the absence of legacy usage" after we mark some method as deprecated? If so then I'd like to slightly reword my suggestion as follows:

> 1. Replace the method name of [§ 22.1.3.10](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-array.prototype.foreach) from `Array.prototype.forEach` to `Array.prototype.each`

> 2. Add a new Annex B entry `§ B.2.6 Additional Properties of the Array.prototype Object > § B.2.6.1 Array.prototype.forEach`, and point to `§ 22.1.3.10`

> 3. Do the same to `%TypedArray%.prototype.forEach` & `Array.prototype.includes`.

And I will not suggest any timeframe this time. I'll leave that to the vendors. Hopefully, this sounds more appealing for implementers.

> **You just made a compromise**

Yes - I said I do not wish to see them *stay*. Compromises, crazy workarounds, and technical debts are all part of an engineer's life. But whenever I get the chance I do look back and see if it's possible to remove those removable technical debts.

**Comment by espadrine** [comment]
Fundamentally, the standard is not there to dictate what browsers will do. It is an effort in compromise between the implementors. If the standard said “Switch to .each”, the browser vendors would look at how many websites would break and say “No”. I think the Acid tests contributed to the belief that browsers just implement what the gods designed. In reality, the Acid tests themselves were modified based on browser feedback.

Another way of looking at it is the [Priority of Constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies). You are an author, and when making a decision, your pick is overruled by whatever is better for the user. In some cases, when the removal of a feature benefits browser performance for the majority while impacting a number of users below a certain threshold, that removal was considered an overall benefit. That is the thinking behind the removal of Flash in Chrome — but, critically, that is a *browser decision*, not a standard decision. The same goes for E4X.

So, what happens when MDN says a feature is deprecated? Browsers talk about the best course of action. They have internal tools that track the number of users that would be impacted by a change. If they estimate that the number is low enough, they may perform that change, and the change is then also written in standards.

I don't see the removal of .forEach happening any time soon — even in 100 years — as it is heavily used. You could have argued for the mere addition of .each, but as mentioned, that has its own wealth of issues. I understand that you care more about absolute purity than the risk of breakage, and honestly, I agree. If I could change the laws of the universe, I would probably remove the speed of light limit… but as you might imagine, everybody might die.

**Comment by jorendorff** [comment]
> Hi @jorendorff, I appreciate the majority of your input which perfectly explained the concerns from a browser vendor's standpoint, but I do not appreciate your last line of tongue-in-cheek. [...] Asking someone to turn around and get lost simply because he doesn't resonate with yours, or your organization's POV, is just disrespectful.

I meant no disrespect with that last line, and I tried to make it as friendly as I could. I see now that it's a crummy attitude, though. Let me take it back and rephrase.

We hear this a lot. Everybody wants some minor, incompatible change. We disagree about the costs and benefits in a very typical, boring way. Your position is that

* *to developers*, breaking compatibility is actually more benefit than cost, because the new spelling will be so much better; and

* the cost *to web users* of breaking compatibility is negligible.

Neither of these statements is anywhere near being true, but I'm not sure how to convince you of that if it isn't obvious. Maintenance costs are more than you think. The amount of JS code on the internet that is not actively maintained (and the extent to which that code still matters) is more than you think. And that's pretty much it.

We also disagree on how valuable this change is, but this is already too long.

> [re: E4X] I am sure there were at least some standards-compliant websites that gone broken in the wild when the plug was pulled as well.

I helped remove that, and I'm honestly not aware of *any* web sites that broke.

But assuming there were a few: Competitively, it's a lot easier breaking a web site that already doesn't work in any other browser.

**Comment by gsklee** [comment]
@espadrine @jorendorff point taken, thanks for sharing your views 😃

**Pull request closed without merging**
