### PR TITLE
order by last-presented date

### PR DESCRIPTION
**Pull request by broofa**
'might as well order by *something* here, and last-presented date gives a sense of which of these are most likely to actually move on to stage 2

### CODE REVIEW

**Comment by ljharb** [comment]
They are already ordered by something - stage entry date.

The last presented date doesn't actually convey likelihood of advancing.

**Comment by broofa** [comment]
> They are already ordered by something - stage entry date.

Huh.  That is not at all obvious.  It would help if stage entry date were actually shown in the table (... although I don't know what value there would be in that.)

Is there any advantage to this other than avoiding having to reorder rows when proposals are presented?

> The last presented date doesn't actually convey likelihood of advancing.

It speaks to which proposals are actively getting attention from the authors and committee though, doesn't it?  Surely that _correlates_ to whether a proposal might advance... no?

FWIW, my goal is to make it easier for readers researching the TS39 pipeline to understand which proposals are actively being developed vs. those that have stagnated.    (There's pretty clearly a non-trivial %'age of proposals that have stalled out).

**Comment by ljharb** [comment]
No, I don't think it does correlate to that - and I think sorting by "last presented" date would indeed suggest that it *is* correlated, which would be a mistake.

I don't think there's any way, short of reading each proposal itself, to know if a proposal has stagnated or not.

**Comment by liyuhang1997** [comment]
Maybe use a website to do this.

**Comment by ljharb** [comment]
The challenge is that really it's only the proposal champion(s) that can tell you if a proposal has stalled. There's plenty of proposals that have seen no updates in years but are still *absolutely* going concerns, it's just that the champions haven't had the time to work on the proposal.

**Pull request closed without merging**
