### PR TITLE
Add "use module"; pragma Stage 1 proposal

### PR DESCRIPTION
**Pull request by chicoxyzzy**
According to https://github.com/tc39/agendas/commit/c5145c693465254913d401eb83d5e73aea8b0230

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks, but this should only be done by proposal champions.

**Comment by chicoxyzzy** [comment]
Out of curiosity, do you remember when this proposal achieved stage 1? All I found was [this](https://github.com/tc39/tc39-notes/blob/master/es7/2017-01/jan-25.md#13iia-proposed-grammar-change-to-es-modules)

**Comment by ljharb** [comment]
I don't believe it has achieved any stage. The referenced meeting hasn't happened yet, and it's not out of the questions for proposals to jump straight to a stage from nothing.

**Comment by chicoxyzzy** [comment]
Yes, that's strange because it's mentioned as a Stage 1 proposal in [proposal repo's readme.md](https://github.com/tc39/proposal-modules-pragma#status).
🤔

**Comment by leobalter** [comment]
@ljharb it's a weird stage 1, but it's something that didn't have a specific repo before this agenda.

https://github.com/rwaldron/tc39-notes/blob/517a0ac88770d51480d41f70302a62a4f5e195db/es7/2016-11/dec-1.md#12iie-variation-on-unambiguousjavascriptgrammar

cc @dherman

**Comment by ljharb** [comment]
Gotcha - this should definitely be added, but it's still up to the proposal champions to do so.

**Pull request closed without merging**
