### PR TITLE
Add Async/Await Alternative Proposal

### PR DESCRIPTION
**Pull request by popey456963**
Proposal to add an alternative Async/Await syntax to Javascript.

https://github.com/popey456963/proposal-alternative-async-await

### CODE REVIEW

**Comment by loganfsmyth** [comment]
Please see https://github.com/tc39/proposals/blob/master/CONTRIBUTING.md#proposals. Before submitting a proposal, it would need to have a TC39 champion to back it.

**Comment by popey456963** [comment]
Is one not able to champion their own proposal?  And if not, how does one know who is capable of being a champion and who is not?

Apologies if these questions are simple, I've tried to read everything around this area but haven't seen anything about the people, more about what the proposal needs to be.

**Comment by ljharb** [comment]
Only at a TC39 committee member is able to champion proposals.

async functions are officially in the spec for ES 2017. An alternative proposal is quite a bit too late, I think.

**Comment by popey456963** [comment]
Ah, damnit, and people seemed so happy.

Well, thanks for your time!

**Comment by mkay581** [comment]
To clarify, I think alternatives and improvements can be made to the spec as long as they remain backwards-compatible.

@popey456963 I would encourage you to find a champion that believes in your proposal. es-discuss, WICG, and the folks that participate on those forums can offer more assistance. Some champions are very active on those forums too.

**Pull request closed without merging**
