### PR TITLE
BigInt to stage 4

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Oh sorry, I didn't know about that. Are these criteria should only be met by features looking for stage 4?

**Comment by ljharb** [comment]
Yes - specifically, to be eligible for stage 4, editors have to have signed off on a PR to the spec repo.

**Comment by chicoxyzzy** [comment]
Indeed. Sorry for my rush.

**Comment by littledan** [comment]
I think it's time to land this PR.

**Comment by ljharb** [comment]
https://github.com/tc39/ecma262/pull/1515 has just received final editor approval today; as such, BigInt now meets all stage 4 criteria. Rebasing and merging.

**Pull request merged**
