### PR TITLE
Move named capture groups to finished proposals

### PR DESCRIPTION
**Pull request by adrianheine**

### CODE REVIEW

**Comment by littledan** [comment]
I was imagining that proposals would move to finished once they were merged into the main spec. However, these don't seem to be merged yet.

**Comment by adrianheine** [comment]
Sure, that makes sense. In that case this PR could just remain open until the others are merged, right?

**Comment by ljharb** [comment]
Yes, that’s fine. Generally we prefer champions to make their own PRs for their proposals, though :-)

**Comment by adrianheine** [comment]
Ok, sorry if I'm not actually helpful.

**Comment by ljharb** [comment]
@adrianheine not at all, your PR is impeccable :-) just a bit premature, is all. We’ll leave it open until the timing is right.

**Comment by mathiasbynens** [comment]
`dotAll` is now merged.

**Comment by adrianheine** [comment]
I opened a [new PR](#105) with just dotall.

**Comment by adrianheine** [comment]
Squashed and rebased.

**Comment by ljharb** [comment]
Linking to https://github.com/tc39/ecma262/pull/1027

**Comment by chicoxyzzy** [comment]
https://github.com/tc39/ecma262/pull/1027 is merged

**Pull request merged**
