### PR TITLE
Updated Decorators Proposal Link and Authors

### PR DESCRIPTION
**Pull request by vramana**

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks! Typically proposal champions are the ones who make changes to their proposals - @wycats @bterlson @jonathandturner for confirmation.

**Comment by bterlson** [comment]
is accurate. Thanks!

**Comment by jonathandturner** [comment]
Sadness... and with that I'm written out of history.  ;)

**Comment by bterlson** [comment]
@jonathandturner who are you guys and what kind of name is Jonath?

**Comment by jonathandturner** [comment]
@bterlson we go everywhere together!

In all seriousness, great work on pushing this forward.  Happy to do the first few steps with @wycats and watch you guys take it farther.

**Pull request merged**
