### PR TITLE
Demote "JSON Modules" to stage 2

### PR DESCRIPTION
**Pull request by jugglinmike**
In [the January/February meeting of TC39](https://github.com/tc39/agendas/blob/main/2023/01.md), [the committee resolved](https://github.com/tc39/notes/blob/8dbaa7c11ad39674a601ecc02af72e58d62b1519/meetings/2023-01/feb-02.md#conclusionresolution-1) to demote the "Import assertions" proposal to "Stage 2," with the understanding that the syntax and semantics may change. I was not present, and I can't find any mention of the impact this ought to have on the "JSON modules" proposal in the meeting notes.

The JSON modules proposal "builds on the import assertions proposal." TC39's process document doesn't explicitly account for inter-proposal dependencies, but by my reading, the JSON modules proposal's specification text can no longer be considered "complete," so it must also be demoted.

### CODE REVIEW

**Comment by ljharb** [comment]
This isn’t something that achieved consensus, so it’d need plenary to do it, and i don’t think this actually makes sense - it remains possible for an implementation to allow importing JSON without import assertions, it’s just that none currently do.

**Comment by leonardoadame** [comment]
#472.pull tequest jugglinmike:demote-json-modules

**Comment by six-ponies** [comment]
您好，您的邮件已收到，我将尽快给您回复。谢谢

**Comment by bzk1994** [comment]
你好，来信已收到

**Comment by ljharb** [comment]
Given that import attributes is now again stage 3 (0a18912), i think this can be closed.

**Pull request closed without merging**
