### PR TITLE
change flatten to flat in flatMap proposal

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Comment by leobalter** [comment]
@michaelficarra would you mind using a more explicit notation for the method names? `{flatMap,flat}` is easier to read.

Otherwise, +1 to merge.

**Comment by michaelficarra** [comment]
@leobalter Done.

**Comment by mathiasbynens** [comment]
Will the Test262 feature tag change as well?

**Comment by leobalter** [comment]
@mathiasbynens thanks for the reminder. cc @rwaldron

**Comment by leobalter** [comment]
https://github.com/tc39/test262/pull/1569

**Pull request merged**
