### PR TITLE
Add proposal-math-float

### PR DESCRIPTION
**Pull request by munrocket**
I am added Daniel Ehrenberg (@littledan) in champion column as an example, but maybe he will.

### CODE REVIEW

**Comment by ljharb** [comment]
Please see https://github.com/tc39/ecma262/blob/HEAD/CONTRIBUTING.md ; it’s premature to make a PR to this repo until a delegate has decided to champion a proposal.

**Comment by munrocket** [comment]
Stage -1 is actually idea thread in discourse.
Seems that I created topic in a wrong section there.

**Comment by munrocket** [comment]
@ljharb seems that I created topic in a wrong section in discourse and can't remove/move or edit it.

**Comment by ljharb** [comment]
Done.

**Pull request closed without merging**
