### PR TITLE
New Proposal: await spread operator

### PR DESCRIPTION
**Pull request by tugrul**

### CODE REVIEW

**Comment by mhofman** [comment]
See https://github.com/tc39/proposal-await.ops

**Comment by tugrul** [comment]
> See https://github.com/tc39/proposal-await.ops

I see similar solution but they are completely different approach. You know, spread operator can composable like below.

```js
[...[1,2,3], ...[4,5,6]]
```

Also they can usable with objects.

```js
{...{name: 'foo'}, ...{surname:'bar'}}
```

**Comment by ljharb** [comment]
Either way, this is not how new proposals are added. Only TC39 delegates can champion a proposal; see https://github.com/tc39/ecma262/blob/HEAD/CONTRIBUTING.md#creating-a-new-proposal

**Comment by tugrul** [comment]
> Either way, this is not how new proposals are added. Only TC39 delegates can champion a proposal; see https://github.com/tc39/ecma262/blob/HEAD/CONTRIBUTING.md#creating-a-new-proposal

Ok. You have to close #393 in this way. You could ask update this pull request instead of closing.

**Comment by ljharb** [comment]
No, i don't, because that PR is by a TC39 delegated.

There's no possible update to be made; it's not a TC39 proposal until it's gotten a champion.

**Pull request closed without merging**
