### PR TITLE
Add New Set methods and Collection methods proposals

### PR DESCRIPTION
**Pull request by chicoxyzzy**
cc @gsathya

### CODE REVIEW

**Comment by zloirock** [comment]
It's splitted to 2 proposals, this and https://github.com/Ginden/collection-methods

**Comment by chicoxyzzy** [comment]
Both are stage 1?

**Comment by zloirock** [comment]
I don't know.

**Comment by ljharb** [comment]
(Please allow proposal champions, only, to make PRs adding proposals to the table)

@gsathya, can you confirm?

**Comment by zloirock** [comment]
BTW, what's the stage of https://github.com/Ginden/map-methods or it's just a placeholder?

**Comment by gsathya** [comment]
> BTW, what's the stage of https://github.com/Ginden/map-methods or it's just a placeholder?

Yeah, I think that was created before the last tc39 meeting. We should merge this into https://github.com/Ginden/collection-methods

cc @Ginden

**Comment by Ginden** [comment]
@gsathya Content from `map-methods` is already integrated into collection-methods.

**Pull request merged**
